import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Grid } from "@mui/material";
import { StyledRightsideContentGrid } from "../style/StyledRightsideContentGrid.style";
import LeftsideBar from "@/component/leftsideBar";
import CustomBox from "@/style/CustomBox.style";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TaskLikho",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CustomBox
        // className="main-container"
        >

        <Grid
          container
          height={"100vh"}
          
        >
          {/* Left side bar start*/}
          <Grid
            item
            size={{ md: 3, lg: 3, xl: 2 }}
            className='leftSidebar'
          //  sx={{ border: '2px solid yellow' }}
          >
            <LeftsideBar />

          </Grid>
          {/* Left side bar end*/}


          {/* Right side content start */}
          <StyledRightsideContentGrid
            item
            size={{ md: 3, lg: 9, xl: 8 }}
          >
            {children}

          </StyledRightsideContentGrid>
          {/* Right side content end */}
        </Grid>
        </CustomBox>
      </body>
    </html>
  );
}
