# This workflow is triggered on pushes to the "staging-main" branch  then build it and merge it to main branch.
name: Integration of branches and pull requests 

on:
  push:
    branches: [ "staging-main" ]


jobs:
  build-and-merge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          Backend/package-lock.json
          client/package-lock.json
 
    - name: Install Dependencies
      working-directory: ./Backend
      run: npm install
      
    - name: Install Dependencies
      working-directory: ./client
      run: npm install

    - name: Build Client
      run: npm run build
      working-directory: ./client
    
    - name: Auto merge
      uses: devmasx/merge-branch@v1.4.0
      with:
        type: now
        from_branch: staging-main
        target_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}